name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Configure Git
        run: |
          git config --global user.name "pastastick"
          git config --global user.email "harun.y.1358@gmail.com"
          
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://$HF_TOKEN@huggingface.co/spaces/PastaStick/Simple_Math_AI main
